### PR TITLE
💄 Update feed tabs

### PR DESCRIPTION
**Pull request by nwingt**

### CODE REVIEW

**Comment by williamchong** [comment]
Currently the feature feed turn into global super like feed, after user logged in and is a super liker. Do we want to show the global super like feed also?

**Comment by nwingt** [comment]
Thanks for reminding me. Updated.

**Comment by williamchong** [comment]
But if you remove `getFetchSuggestArticlesApi ` we will be show global super like feed to guest in frontpage, which might contain spam.
My previous comment was more on about should we show the global super like feed to logged in super likers.

**Comment by nwingt** [comment]
Confirmed with @joshkiu. Super Like global feed is not shown to signed-in users

**Review by williamchong — APPROVED** [review]

**Pull request merged**
