### PR TITLE
[TAS-2016] 🔧 Allow scripted content for ePub reader

### PR DESCRIPTION
**Pull request by nwingt**

### CODE REVIEW

**Review by williamchong — APPROVED** [review]
Will use iframe + book3app in the future

**Review by williamchong — CHANGES_REQUESTED** [review]
@nwingt on second thought, we actually hard code a list of class id that can run script instead of enabling for all

**Comment by nwingt** [comment]
How about owner wallet?

**Comment by williamchong** [comment]
> How about owner wallet?

Would also work but unless aome wallet always has interactive book, class id is safer

**Review by williamchong — APPROVED** [review]

**Pull request merged**
