### PR TITLE
🚸 Blocking update ownerList after transferring NFT

### PR DESCRIPTION
**Pull request by WeiJun0827**

### CODE REVIEW

**Review by nwingt — COMMENTED** [review]
Should show some loading UI while blocking?

**Comment by WeiJun0827** [comment]
> Should show some loading UI while blocking?

I think currently it just extends the processing time a bit, should we explicitly let user know the state?

**Comment by nwingt** [comment]
How about moving that line to the following lines, perhaps using `Promise.all()` with collected count?
https://github.com/likecoin/liker-land/blob/4d3479b8a0d87c618f7e48ee49b88d84b1cc0ef3/src/mixins/nft.js#L604-L605

**Comment by WeiJun0827** [comment]
> How about moving that line to the following lines, perhaps using `Promise.all()` with collected count?
> 
> https://github.com/likecoin/liker-land/blob/4d3479b8a0d87c618f7e48ee49b88d84b1cc0ef3/src/mixins/nft.js#L604-L605

Agreed and updated.

**Review by nwingt — APPROVED** [review]

**Pull request merged**
