### PR TITLE
🐛 Fix fetching ownCount when not login

### PR DESCRIPTION
**Pull request by AuroraHuang22**

### CODE REVIEW

**Review by WeiJun0827 — APPROVED** [review]

**Review by williamchong — CHANGES_REQUESTED** [review]
i think owner info loading should not be true, nor should owner info api be called if address is not set...

**Comment by AuroraHuang22** [comment]
> i think owner info loading should not be true, nor should owner info api be called if address is not set...

`isOwnerInfoLoading` should has been injected from the [mixin](https://github.com/likecoin/liker-land/blob/master/src/mixins/nft.js#:~:text=isOwnerInfoLoading%3A%20false%2C), 
and the relative API won't be called if the address is empty.
https://github.com/likecoin/liker-land/blob/master/src/mixins/nft.js#:~:text=async-,updateUserCollectedCount,-(classId%2C

**Comment by williamchong** [comment]
> > i think owner info loading should not be true, nor should owner info api be called if address is not set...
> 
> `isOwnerInfoLoading` should has been injected from the [mixin](https://github.com/likecoin/liker-land/blob/master/src/mixins/nft.js#:~:text=isOwnerInfoLoading%3A%20false%2C), and the relative API won't be called if the address is empty. https://github.com/likecoin/liker-land/blob/master/src/mixins/nft.js#:~:text=async-,updateUserCollectedCount,-(classId%2C

then do we still need to check for !!address in this case after removing data?

**Comment by nwingt** [comment]
I think the initial value of `isOwnerInfoLoading` can be `!!getters.getAddress` and no need to check for `!!getAddress`

**Pull request merged**
