### PR TITLE
📈 Update tipping related events

### PR DESCRIPTION
**Pull request by AuroraHuang22**

### CODE REVIEW

**Review by williamchong — APPROVED** [review]

**Review by nwingt — COMMENTED** [review]
We can also watch `open` prop to keep `NFTTippingOpen` event for generic event

**Comment by nwingt** [comment]
Also, I have found the following event names rather confusing
https://github.com/likecoin/liker-land/blob/82f3dc26d2514c6dfd8c692f442e8c77d16df65c/src/pages/nft/class/_classId/index.vue#L1418-L1427
https://github.com/likecoin/liker-land/blob/82f3dc26d2514c6dfd8c692f442e8c77d16df65c/src/pages/nft/collection/_collectionId/index.vue#L456-L463

@williamchong Ignore or rename?

**Comment by AuroraHuang22** [comment]
> Also, I have found the following event names rather confusing
> 
> https://github.com/likecoin/liker-land/blob/82f3dc26d2514c6dfd8c692f442e8c77d16df65c/src/pages/nft/class/_classId/index.vue#L1418-L1427
> 
> 
> https://github.com/likecoin/liker-land/blob/82f3dc26d2514c6dfd8c692f442e8c77d16df65c/src/pages/nft/collection/_collectionId/index.vue#L456-L463
> 
> @williamchong Ignore or rename?

I've already renamed this in another PR (not yet open for review.

**Comment by nwingt** [comment]
> > Also, I have found the following event names rather confusing
> > https://github.com/likecoin/liker-land/blob/82f3dc26d2514c6dfd8c692f442e8c77d16df65c/src/pages/nft/class/_classId/index.vue#L1418-L1427
> > 
> > https://github.com/likecoin/liker-land/blob/82f3dc26d2514c6dfd8c692f442e8c77d16df65c/src/pages/nft/collection/_collectionId/index.vue#L456-L463
> > 
> > @williamchong Ignore or rename?
> 
> I've already renamed this in another PR (not yet open for review.

OK

**Pull request merged**
