### PR TITLE
🐛 Fix cannot resume canceled subscription

### PR DESCRIPTION
**Pull request by williamchong**

### CODE REVIEW

**Review by nwingt — APPROVED** [review]
Using DELETE for resuming is a bit weird though

**Comment by williamchong** [comment]
couldn't find a good existing endpoint just for POSTing a resume, so i guess DELETE the cancel still make some sense...

**Comment by nwingt** [comment]
Hotfix is ok

**Review by nwingt — APPROVED** [review]

**Comment by williamchong** [comment]
@nwingt on second thought maybe the change will affect those actually expired, so I am splitting the `isCivicLikerRenewalPeriod` and `willCancel` case

**Pull request merged**
